trigger:
- none

pool: 'TestAgentPool'

steps:
- checkout: self
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    allowTelemetryCollection: false