trigger:
- none

pool: 'TestAgentPool'

steps:
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\quick-test-cluster-deploy01'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)quick-test-cluster-deploy01'
    allowTelemetryCollection: false