trigger:
- none

pool: 'TestAgentPool'

steps:
#- checkout: self
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: 'artifacts-name'
    publishLocation: 'pipeline'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    allowTelemetryCollection: false